$(document).ready(function() {

  var klausurTermineTabelle = $('#klausurTermineTabelle').DataTable();
  //HERE WE HAVE TO ESTABLISH CONNECTION TO THE DATABASE
  //KLASS NAME THAT THE SIGNED IN STUDENT BELONGS TO HAS TO BE ADDED TO THE END OF THE TITLE
  //FOR-LOOP HAS TO BE CREATED INSIDE THIS FUNCTION TO ADD ALL DATABASE KLAUSUR ENTRIES FOR THIS
  //SPECIFIC KLASS INTO A TABLE
  $("#klausurTermineTitel").text("Klausurtermine - " + "KLASS NAME");
});
